### PR TITLE
Refactor model and likelihoods to allow swapping in

### PR DESCRIPTION
**Pull request by nishadgothoskar**

### CODE REVIEW

**Review by horizon-blue — COMMENTED** [review]
Thanks for the refactoring! It's really great that we are starting to have a unified format.:)

Eventually I think it will be great if we can programmatically switch between the likelihood function without having to change the source code, e.g. by passing in the name of the likelihood, or even the functions themselves, as hyperparameters, or using factory functions like you did before.

One small nit: in https://github.com/probcomp/b3d/pull/128 George defined a few tests that depends on `kfold_image_kernel.py` (e.g. [this one](https://github.com/probcomp/b3d/blob/9632e9d91d216b1912fd29adefc14dbd8b25f905/tests/dynamic_object_model/test_pixel_distribution.py)), which are going to crash now since we restructure the files. We might want to update the imports there as we rename the files :).

**Comment by nishadgothoskar** [comment]
Thanks for catching that. I'll update now

**Comment by nishadgothoskar** [comment]
Updated the tests and now they pass

**Review by horizon-blue — APPROVED** [review]
LGTM!

**Pull request merged**
