### PR TITLE
Fix trimesh usage in tests

### PR DESCRIPTION
**Pull request by eightysteele**
This PR fixes a test failure related to `AttributeError` caused by `trimesh` usage:

1. `trimesh.load()` now uses `force="mesh"`, see: https://github.com/mikedh/trimesh/issues/1585
2. removes `to_color()` which doesn't exist

After these changes, the test passes.

### CODE REVIEW

**Comment by georgematheos** [comment]
I haven't checked runtests.sh on my end for this, but if the tests still pass with this change, I approve it!

**Comment by eightysteele** [comment]
There are actually some other tests and source files with similar `trimesh` usage, but I don't have enough context to fix them without some help :)

```bash
λ grep -rn "trimesh.load" src/
src/b3d/mesh.py:130:        trimesh_mesh = trimesh.load_mesh(path, process=False, validate=False)
src/b3d/utils.py:199:    box_mesh = trimesh.load(os.path.join(b3d.get_assets_path(), "objs/cube.obj"))
src/b3d/renderer/torch/renderutils/diffdope.py:790:#         mesh = trimesh.load(self.path_model, force="mesh")

λ grep -rn "trimesh.load" tests/
tests/test_mug_handle_posterior.py:35:        mesh = trimesh.load(mesh_path, force="mesh")
tests/test_mug_smc_pose_inference_synthetic_and_real.py:76:        object_library.add_trimesh(trimesh.load(mesh_path, force="mesh"))
tests/test_render_ycb_model.py:14:    mesh = trimesh.load(mesh_path)
tests/test_image_posterior_resolution_invariance.py:59:        mesh = trimesh.load(MESH_PATH, force="mesh")
tests/test_likelihood_invariances.py:21:    mesh = trimesh.load(mesh_path, force="mesh")
tests/test_likelihood_invariances.py:97:    mesh = trimesh.load(mesh_path, force="mesh")
tests/sama4d/data_curation.py:114:    mesh = trimesh.load(mesh_path)
tests/dlpack.py:16:mesh = trimesh.load(mesh_path)

λ grep -rn "to_color()" tests/
tests/dlpack.py:21:vertex_colors = jnp.array(mesh.visual.to_color().vertex_colors)[..., :3] / 255.0

λ grep -rn "to_color()" src/
src/b3d/mesh.py:141:                jnp.array(trimesh_mesh.visual.to_color().vertex_colors)[..., :3] / 255.0
src/b3d/utils.py:235:    vertex_colors = jnp.array(mesh.visual.to_color().vertex_colors)[..., :3] / 255.0
src/b3d/bayes3d/mesh_library.py:89:        vertex_colors = jnp.array(mesh.visual.to_color().vertex_colors)[..., :3] / 255.0
```

**Comment by georgematheos** [comment]
@eightysteele I see.  Are these tests currently failing?

In general I think I have lost track of the status of running the tests on your end.  On my end, `./run_tests.sh` passed on main last time I checked (a couple days ago), but it is possible I have outdated dependencies in my conda environment.

In any case, happy to align on this and help however I can -- but also feel free to just merge this if you are tracking the status of getting the tests running in the environment; I don't want to slow you down here!

**Comment by eightysteele** [comment]
@georgematheos sounds good! yeah, i think i'll get them passing on my end first, before merging this in. thanks!

**Pull request closed without merging**
