### PR TITLE
Gm/conv patch tracking

### PR DESCRIPTION
**Pull request by georgematheos**
@nishadgothoskar This is my patch tracking code.  Feel free to review, otherwise I will plan to merge tomorrow.

### CODE REVIEW

**Comment by georgematheos** [comment]
@mirkoklukas can you please quickly sign off on the changes I made to FeatureTrackData?

**Comment by georgematheos** [comment]
@eightysteele it appears that this has changed the `pixi.lock`.  This branch is not intended to change any dependencies.  Does this indicate that I should revert the `pixi.lock` in this branch to the same version as on main, or is there a reason the `pixi.lock` could change on a branch like this that we would want to keep?

**Comment by eightysteele** [comment]
@georgematheos tl;dr it looks like `main` got merged into this branch without pulling the latest?

```bash
git log --merges
commit fe81201b25ee6942b24adb2281378d5159d87586 (HEAD -> gm/conv_patch_tracking, origin/gm/conv_patch_tracking)
Merge: a8baba9 6a96f94
Author: George Matheos <georgematheos@gmail.com>
Date:   Tue Aug 13 23:10:12 2024 +0000
    Merge branch 'main' into gm/conv_patch_tracking
 ```
 
 so `main` commit [6a96f94](https://github.com/probcomp/b3d/commit/6a96f940b241205d95e7389e573b690658893133) is from yesterday and we're now a few commits ahead of that one. since `pyproject.toml` has changed between those, `pixi` tried solving the difference and updated `pixi.lock`.
 
 a `git revert` might be the way to go. i left some commentary in slack. :)

**Comment by eightysteele** [comment]
see #110 💥

**Comment by georgematheos** [comment]
Replaced by #110.

**Comment by sritchie** [comment]
Could you guys have just merged main again?

**Pull request closed without merging**
